camel:
  springboot:
    # The Camel context name
    name: CamelRestGesdoc
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /api/*

# Binding health checks to a different port
# change actuator endpoints path
management:
  server:
    port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
